version: '3.8'
services:
  healthy-backend:
    restart: always
    container_name: healthy-backend
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    env_file:
      - ../../.env
    ports:
      - ${PORT}:${PORT}
   